name: AI Service Release nightly image

on:
  push:
    branches: [main]
    paths:
      - 'wren-ai-service/**'

env:
  WREN_AI_SERVICE_IMAGE: ghcr.io/${{ github.repository_owner }}/wren-ai-service

defaults:
  run:
    working-directory: wren-ai-service

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare tag name
        id: tag-preparation
        run: |
          tag_name=main-$(git log -1 --pretty=%h)
          echo "TAG_NAME=$tag_name" >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.WREN_AI_SERVICE_IMAGE }}
          tags: |
            type=raw,value=${{ steps.tag-preparation.outputs.TAG_NAME }}
            type=raw,value=nightly
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./wren-ai-service
          file: ./wren-ai-service/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
