name: Wren-UI Release stable image

on:
  workflow_dispatch:
    inputs:
      version:
        description: Give a version for this release
        type: string
        required: true

env:
  WREN_UI_IMAGE: ghcr.io/${{ github.repository_owner }}/wren-ui

defaults:
  run:
    working-directory: wren-ui

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.WREN_UI_IMAGE }}
          tags: |
            type=raw,value=${{ github.event.inputs.version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./wren-ui
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
  merge:
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.WREN_UI_IMAGE }}:${{ github.event.inputs.version }}
  tag-ui-version:
    runs-on: ubuntu-latest
    needs: [merge]
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
      - name: Set up Git
        run: |
          git config --global user.name "wren-ai[bot]"
          git config --global user.email "dev@cannerdata.com"
      - name: Generate and Save Change Log
        id: changelog
        run: |
          echo "Generating change log..."
          PREVIOUS_VERSION=release/ui/$(jq -r '.version' package.json)
          echo "Previous version: $PREVIOUS_VERSION"
          echo "================ change log ================"
          CHANGE_LOG=$(git log --pretty=format:"%s" $PREVIOUS_VERSION..HEAD | grep wren-ui)
          echo "================ change log ================"

          # Separate the change log into categories
          FEATURES=$(echo "$CHANGE_LOG" | grep "^feat" | sed 's/^/- /')
          FIXES_AND_CHORES=$(echo "$CHANGE_LOG" | grep -E "^(fix|chore)" | sed 's/^/- /')

          # Create the full change log
          FULL_CHANGE_LOG="\nChangelog for the version\n"
          if [ -n "$FEATURES" ]; then
            FULL_CHANGE_LOG+="\nFeature and Enhancement\n$FEATURES"
          fi
          if [ -n "$FIXES_AND_CHORES" ]; then
            FULL_CHANGE_LOG+="\n\nFixes and Chores\n$FIXES_AND_CHORES"
          fi

          {
            echo "CHANGE_LOG<<EOF"
            echo -e "$FULL_CHANGE_LOG"
            echo EOF
          } >> $GITHUB_ENV
      - name: Update Wren-UI version
        run: |
          version=${{ github.event.inputs.version }}
          sed -i 's/"version": "[^"]*"/"version": "'"$version"'"/' package.json
          git add package.json
          git commit -m "update wren-ui version to $version"
          git push
          git tag -a "release/ui/$version" -m "${{ env.CHANGE_LOG }}"
          git push origin "release/ui/$version"
