name: Wren-UI Release image

on:
  workflow_dispatch:
    inputs:
      docker_image_tag_name:
        description: Docker image tag name (optional, default branch name/tag name replaced with hyphens)
        type: string

env:
  WREN_UI_IMAGE: ghcr.io/${{ github.repository_owner }}/wren-ui

defaults:
  run:
    working-directory: wren-ui

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare tag name
        id: tag-preparation
        run: |
          if [ -n "${{ github.event.inputs.docker_image_tag_name }}" ]; then
            tag_name=${{ github.event.inputs.docker_image_tag_name }}
          else
            tag_name=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9]/-/g')-$(git log -1 --pretty=%h)
          fi
          echo "TAG_NAME=$tag_name" >> $GITHUB_OUTPUT
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.WREN_UI_IMAGE }}
          tags: |
            type=raw,value=${{ steps.tag-preparation.outputs.TAG_NAME }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./wren-ui
          platforms: linux/amd64
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
